-- ============================================================================
-- MSTP_ACCOUNT_MAPPING 收款账号映射表
-- ============================================================================

CREATE TABLE MSTP.MSTP_ACCOUNT_MAPPING (
    ID              NUMBER(20)      NOT NULL,
    ACCOUNT_NO      VARCHAR2(32)    NOT NULL,
    ACCOUNT_NAME    VARCHAR2(200)   NOT NULL,
    CURRENCY        VARCHAR2(3)     NOT NULL,
    ACCOUNT_TYPE    VARCHAR2(10)    NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    REMARK          VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ACCOUNT_MAPPING PRIMARY KEY (ID),
    CONSTRAINT CK_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('INTERNAL', 'EXTERNAL')),
    CONSTRAINT CK_ACCOUNT_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_ACCOUNT_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_ACCOUNT_NO ON MSTP.MSTP_ACCOUNT_MAPPING (ACCOUNT_NO, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_ACCOUNT_MAPPING IS '收款账号映射表';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ID IS '主键';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ACCOUNT_NO IS '收款账号';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ACCOUNT_NAME IS '收款账户名称';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.CURRENCY IS '币种 ISO 4217';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ACCOUNT_TYPE IS '账户类型: INTERNAL/EXTERNAL';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.STATUS IS '状态: ACTIVE/INACTIVE';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.REMARK IS '备注';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.IS_DELETED IS '软删除: 0-有效 1-已删除';
