-- ============================================================================
-- MSTP_PAYER_ACCOUNT_CONFIG 付款账号配置表
-- ============================================================================

CREATE TABLE MSTP.MSTP_PAYER_ACCOUNT_CONFIG (
    ID                  NUMBER(20)      NOT NULL,
    CHANNEL             VARCHAR2(10)    NOT NULL,
    PAYER_BANK_CODE     VARCHAR2(20)    NOT NULL,
    PAYER_BANK_NAME     VARCHAR2(200)   NOT NULL,
    PAYER_ACCOUNT_NO    VARCHAR2(32)    NOT NULL,
    PAYER_ACCOUNT_NAME  VARCHAR2(200)   NOT NULL,
    CURRENCY            VARCHAR2(3)     NOT NULL,
    IS_AUTHORIZED       NUMBER(1)       DEFAULT 0 NOT NULL,
    AUTHORIZED_TIME     TIMESTAMP(6),
    REMARK              VARCHAR2(500),
    IS_DELETED          NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY          VARCHAR2(50)    NOT NULL,
    CREATED_TIME        TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(50)    NOT NULL,
    UPDATED_TIME        TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYER_ACCOUNT_CONFIG PRIMARY KEY (ID),
    CONSTRAINT CK_PAYER_CHANNEL CHECK (CHANNEL IN ('CNAPS', 'CIPS')),
    CONSTRAINT CK_PAYER_AUTHORIZED CHECK (IS_AUTHORIZED IN (0, 1)),
    CONSTRAINT CK_PAYER_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_CHANNEL_CURRENCY ON MSTP.MSTP_PAYER_ACCOUNT_CONFIG (CHANNEL, CURRENCY, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_PAYER_ACCOUNT_CONFIG IS '付款账号配置表';
COMMENT ON COLUMN MSTP.MSTP_PAYER_ACCOUNT_CONFIG.CHANNEL IS '支付渠道: CNAPS/CIPS';
COMMENT ON COLUMN MSTP.MSTP_PAYER_ACCOUNT_CONFIG.IS_AUTHORIZED IS '是否已授权: 0-否 1-是';
