-- ============================================================================
-- MSTP_REMARK_MAPPING 交易附言映射表
-- ============================================================================

CREATE TABLE MSTP.MSTP_REMARK_MAPPING (
    ID              NUMBER(20)      NOT NULL,
    MATCH_PATTERN   VARCHAR2(100)   NOT NULL,
    REMARK_CHINESE  VARCHAR2(200)   NOT NULL,
    REMARK          VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REMARK_MAPPING PRIMARY KEY (ID),
    CONSTRAINT CK_REMARK_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_MATCH_PATTERN ON MSTP.MSTP_REMARK_MAPPING (MATCH_PATTERN, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_REMARK_MAPPING IS '交易附言映射表';
COMMENT ON COLUMN MSTP.MSTP_REMARK_MAPPING.ID IS '主键';
COMMENT ON COLUMN MSTP.MSTP_REMARK_MAPPING.MATCH_PATTERN IS '匹配规则(与上游remark字段匹配,%结尾为前缀匹配)';
COMMENT ON COLUMN MSTP.MSTP_REMARK_MAPPING.REMARK_CHINESE IS '中文附言(匹配成功后填入支付指令)';
COMMENT ON COLUMN MSTP.MSTP_REMARK_MAPPING.REMARK IS '备注';
COMMENT ON COLUMN MSTP.MSTP_REMARK_MAPPING.IS_DELETED IS '软删除: 0-有效 1-已删除';
