-- ============================================================================
-- MSTP_MESSAGE_EXCEPTION 异常消息表
-- ============================================================================

CREATE TABLE MSTP.MSTP_MESSAGE_EXCEPTION (
    ID              NUMBER(20)      NOT NULL,
    MSG_ID          VARCHAR2(64)    NOT NULL,
    RAW_PAYLOAD     CLOB            NOT NULL,
    EXCEPTION_TYPE  VARCHAR2(20)    NOT NULL,
    ERROR_MESSAGE   VARCHAR2(500)   NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'PENDING' NOT NULL,
    RESOLVED_BY     VARCHAR2(50),
    RESOLVED_TIME   TIMESTAMP(6),
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MESSAGE_EXCEPTION PRIMARY KEY (ID),
    CONSTRAINT CK_ME_STATUS CHECK (STATUS IN ('PENDING', 'RESOLVED'))
);

CREATE INDEX MSTP.IDX_ME_MSG_ID ON MSTP.MSTP_MESSAGE_EXCEPTION (MSG_ID);
CREATE INDEX MSTP.IDX_ME_STATUS ON MSTP.MSTP_MESSAGE_EXCEPTION (STATUS);

COMMENT ON TABLE  MSTP.MSTP_MESSAGE_EXCEPTION IS '异常消息表';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.MSG_ID IS '原始消息ID';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.RAW_PAYLOAD IS '原始消息内容';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.EXCEPTION_TYPE IS '异常类型: FORMAT_ERROR/FIELD_MISSING/INVALID_ENUM/BIZ_ERROR/SYS_ERROR';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.STATUS IS '状态: PENDING/RESOLVED';
