-- ============================================================================
-- MSTP_APPROVAL_RECORD 审批主表
-- ============================================================================

CREATE TABLE MSTP.MSTP_APPROVAL_RECORD (
    ID              NUMBER(20)      NOT NULL,
    APPROVAL_ID     VARCHAR2(40)    NOT NULL,
    BIZ_TYPE        VARCHAR2(20)    NOT NULL,
    BIZ_ID          NUMBER(20)      NOT NULL,
    OPERATION_TYPE  VARCHAR2(10)    NOT NULL,
    OPERATION_DATA  CLOB            NOT NULL,
    ORIGINAL_DATA   CLOB,
    STATUS          VARCHAR2(10)    DEFAULT 'PENDING' NOT NULL,
    MAKER_ID        VARCHAR2(50)    NOT NULL,
    MAKER_TIME      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CHECKER_ID      VARCHAR2(50),
    CHECKER_TIME    TIMESTAMP(6),
    REJECT_REASON   VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APPROVAL_RECORD PRIMARY KEY (ID),
    CONSTRAINT CK_AR_BIZ_TYPE CHECK (BIZ_TYPE IN ('ACCOUNT_MAPPING', 'BANK_MAPPING', 'PAYER_CONFIG')),
    CONSTRAINT CK_AR_OP_TYPE CHECK (OPERATION_TYPE IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT CK_AR_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CK_AR_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_APPROVAL_ID ON MSTP.MSTP_APPROVAL_RECORD (APPROVAL_ID);
CREATE INDEX MSTP.IDX_AR_BIZ_TYPE_STATUS ON MSTP.MSTP_APPROVAL_RECORD (BIZ_TYPE, STATUS);
CREATE INDEX MSTP.IDX_AR_MAKER_ID ON MSTP.MSTP_APPROVAL_RECORD (MAKER_ID);
CREATE INDEX MSTP.IDX_AR_CHECKER_ID ON MSTP.MSTP_APPROVAL_RECORD (CHECKER_ID);

COMMENT ON TABLE  MSTP.MSTP_APPROVAL_RECORD IS '审批主表';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.APPROVAL_ID IS '审批单号';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.BIZ_TYPE IS '业务类型: ACCOUNT_MAPPING/BANK_MAPPING/PAYER_CONFIG';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.OPERATION_TYPE IS '操作类型: CREATE/UPDATE/DELETE';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.OPERATION_DATA IS '操作数据(JSON格式,保存变更前后快照)';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.STATUS IS '审批状态: PENDING/APPROVED/REJECTED';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.MAKER_ID IS '制单人';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.CHECKER_ID IS '审核人';
