-- ============================================================================
-- MSTP_ROLE 角色表
-- ============================================================================

CREATE TABLE MSTP.MSTP_ROLE (
    ID              NUMBER(20)      NOT NULL,
    ROLE_CODE       VARCHAR2(30)    NOT NULL,
    ROLE_NAME       VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    SOURCE          VARCHAR2(10)    DEFAULT 'LOCAL' NOT NULL,
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID),
    CONSTRAINT CK_ROLE_SOURCE CHECK (SOURCE IN ('LOCAL', 'EXTERNAL')),
    CONSTRAINT CK_ROLE_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_ROLE_CODE ON MSTP.MSTP_ROLE (ROLE_CODE, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_ROLE IS '角色表';
COMMENT ON COLUMN MSTP.MSTP_ROLE.ROLE_CODE IS '角色编码';
COMMENT ON COLUMN MSTP.MSTP_ROLE.SOURCE IS '来源: LOCAL/EXTERNAL';

-- ============================================================================
-- Initial Data
-- ============================================================================
INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'MAKER', '制单人', '可新增/编辑映射记录，查询数据', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'CHECKER', '审核人', '可审批映射记录，查询数据', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'ADMIN', '管理员', '拥有所有权限', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'VIEWER', '观察者', '仅查询权限', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);
