-- ============================================================================
-- MSTP_BANK_MAPPING 行号映射表
-- ============================================================================

CREATE TABLE MSTP.MSTP_BANK_MAPPING (
    ID              NUMBER(20)      NOT NULL,
    BANK_CODE       VARCHAR2(20)    NOT NULL,
    BANK_NAME       VARCHAR2(200)   NOT NULL,
    CODE_TYPE       VARCHAR2(10)    NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    REMARK          VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BANK_MAPPING PRIMARY KEY (ID),
    CONSTRAINT CK_BANK_CODE_TYPE CHECK (CODE_TYPE IN ('CNAPS', 'CIPS')),
    CONSTRAINT CK_BANK_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_BANK_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_BANK_CODE ON MSTP.MSTP_BANK_MAPPING (BANK_CODE, CODE_TYPE, IS_DELETED);
CREATE INDEX MSTP.IDX_BANK_CODE_TYPE ON MSTP.MSTP_BANK_MAPPING (BANK_CODE, CODE_TYPE);

COMMENT ON TABLE  MSTP.MSTP_BANK_MAPPING IS '行号映射表';
COMMENT ON COLUMN MSTP.MSTP_BANK_MAPPING.BANK_CODE IS '行号: CNAPS 12位 / CIPS BIC 11位';
COMMENT ON COLUMN MSTP.MSTP_BANK_MAPPING.BANK_NAME IS '行名';
COMMENT ON COLUMN MSTP.MSTP_BANK_MAPPING.CODE_TYPE IS '行号类型: CNAPS/CIPS';
