-- ============================================================================
-- MSTP_PAYMENT_STATUS_LOG 支付状态跟踪表
-- ============================================================================

CREATE TABLE MSTP.MSTP_PAYMENT_STATUS_LOG (
    ID              NUMBER(20)      NOT NULL,
    TXN_ID          VARCHAR2(40)    NOT NULL,
    FROM_STATUS     VARCHAR2(30),
    TO_STATUS       VARCHAR2(30)    NOT NULL,
    STATUS_TIME     TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    REMARK          VARCHAR2(500),
    CREATED_BY      VARCHAR2(50)    DEFAULT 'SYSTEM' NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYMENT_STATUS_LOG PRIMARY KEY (ID)
);

CREATE INDEX MSTP.IDX_PSL_TXN_ID ON MSTP.MSTP_PAYMENT_STATUS_LOG (TXN_ID);
CREATE INDEX MSTP.IDX_PSL_STATUS_TIME ON MSTP.MSTP_PAYMENT_STATUS_LOG (STATUS_TIME);

COMMENT ON TABLE  MSTP.MSTP_PAYMENT_STATUS_LOG IS '支付状态跟踪表';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.TXN_ID IS '交易ID';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.FROM_STATUS IS '原状态';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.TO_STATUS IS '新状态';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.STATUS_TIME IS '状态变更时间';
