-- ============================================================================
-- MSTP_SYS_CONFIG 系统配置表
-- ============================================================================

CREATE TABLE MSTP.MSTP_SYS_CONFIG (
    ID              NUMBER(20)      NOT NULL,
    CONFIG_KEY      VARCHAR2(100)   NOT NULL,
    CONFIG_VALUE    VARCHAR2(500)   NOT NULL,
    CONFIG_GROUP    VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SYS_CONFIG PRIMARY KEY (ID),
    CONSTRAINT CK_SC_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_CONFIG_KEY ON MSTP.MSTP_SYS_CONFIG (CONFIG_KEY, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_SYS_CONFIG IS '系统配置表';
COMMENT ON COLUMN MSTP.MSTP_SYS_CONFIG.CONFIG_KEY IS '配置键';
COMMENT ON COLUMN MSTP.MSTP_SYS_CONFIG.CONFIG_VALUE IS '配置值';
COMMENT ON COLUMN MSTP.MSTP_SYS_CONFIG.CONFIG_GROUP IS '配置分组';

-- ============================================================================
-- Initial Data
-- ============================================================================
INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.host', 'tcp://localhost:55555', 'SOLACE', 'Solace Broker地址', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.vpn', 'mstp-vpn', 'SOLACE', 'Solace消息VPN', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.queue', 'MSTP_PAYMENT_REQ_Q', 'SOLACE', '支付请求队列名', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.concurrent.consumers', '5', 'SOLACE', '初始并发消费者数', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.max.consumers', '20', 'SOLACE', '最大并发消费者数', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.base-url', 'https://payment.internal/api/v1', 'PAYMENT', '下游支付API基础地址', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.connect-timeout', '5000', 'PAYMENT', '连接超时(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.read-timeout', '30000', 'PAYMENT', '读取超时(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.max-retry', '3', 'PAYMENT', '最大重试次数', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.polling.initial-interval', '5000', 'PAYMENT', '轮询初始间隔(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.polling.max-interval', '30000', 'PAYMENT', '轮询最大间隔(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.pending.timeout', '300', 'PAYMENT', 'Pending状态超时时间(秒)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'auth.provider', 'local', 'AUTH', '认证提供者: local/sso', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'auth.local.access-token-ttl', '30m', 'AUTH', 'Access Token有效期', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'rbac.provider', 'local', 'RBAC', '权限提供者: local/external', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'rbac.sync.interval', '300', 'RBAC', '外部权限同步间隔(秒)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

COMMIT;
