-- ============================================================================
-- MSTP_AUDIT_LOG 操作日志表 (仅追加,不可修改)
-- ============================================================================

CREATE TABLE MSTP.MSTP_AUDIT_LOG (
    ID              NUMBER(20)      NOT NULL,
    LOG_ID          VARCHAR2(40)    NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    USER_NAME       VARCHAR2(100)   NOT NULL,
    MODULE          VARCHAR2(30)    NOT NULL,
    ACTION          VARCHAR2(30)    NOT NULL,
    TARGET_TYPE     VARCHAR2(30),
    TARGET_ID       VARCHAR2(40),
    DETAIL          CLOB,
    CLIENT_IP       VARCHAR2(45),
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX MSTP.UK_AUDIT_LOG_ID ON MSTP.MSTP_AUDIT_LOG (LOG_ID);
CREATE INDEX MSTP.IDX_AL_USER_ID ON MSTP.MSTP_AUDIT_LOG (USER_ID);
CREATE INDEX MSTP.IDX_AL_MODULE ON MSTP.MSTP_AUDIT_LOG (MODULE);
CREATE INDEX MSTP.IDX_AL_CREATED_TIME ON MSTP.MSTP_AUDIT_LOG (CREATED_TIME);

COMMENT ON TABLE  MSTP.MSTP_AUDIT_LOG IS '操作日志表(仅追加,不可修改)';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.LOG_ID IS '日志唯一ID';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.MODULE IS '模块';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.ACTION IS '操作';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.DETAIL IS '操作详情(JSON)';
