-- ============================================================================
-- MSTP Mapping Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 收款账号映射表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_ACCOUNT_MAPPING (
    ID              NUMBER(20)      NOT NULL,
    ACCOUNT_NO      VARCHAR2(32)    NOT NULL,
    ACCOUNT_NAME    VARCHAR2(200)   NOT NULL,
    CURRENCY        VARCHAR2(3)     NOT NULL,
    ACCOUNT_TYPE    VARCHAR2(10)    NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    REMARK          VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ACCOUNT_MAPPING PRIMARY KEY (ID),
    CONSTRAINT CK_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('INTERNAL', 'EXTERNAL')),
    CONSTRAINT CK_ACCOUNT_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_ACCOUNT_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_ACCOUNT_NO ON MSTP.MSTP_ACCOUNT_MAPPING (ACCOUNT_NO, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_ACCOUNT_MAPPING IS '收款账号映射表';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ID IS '主键';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ACCOUNT_NO IS '收款账号';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ACCOUNT_NAME IS '收款账户名称';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.CURRENCY IS '币种 ISO 4217';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.ACCOUNT_TYPE IS '账户类型: INTERNAL/EXTERNAL';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.STATUS IS '状态: ACTIVE/INACTIVE';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.REMARK IS '备注';
COMMENT ON COLUMN MSTP.MSTP_ACCOUNT_MAPPING.IS_DELETED IS '软删除: 0-有效 1-已删除';

-- ----------------------------------------------------------------------------
-- 2. 行号映射表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_BANK_MAPPING (
    ID              NUMBER(20)      NOT NULL,
    BANK_CODE       VARCHAR2(20)    NOT NULL,
    BANK_NAME       VARCHAR2(200)   NOT NULL,
    CODE_TYPE       VARCHAR2(10)    NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    REMARK          VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BANK_MAPPING PRIMARY KEY (ID),
    CONSTRAINT CK_BANK_CODE_TYPE CHECK (CODE_TYPE IN ('CNAPS', 'CIPS')),
    CONSTRAINT CK_BANK_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_BANK_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_BANK_CODE ON MSTP.MSTP_BANK_MAPPING (BANK_CODE, CODE_TYPE, IS_DELETED);
CREATE INDEX MSTP.IDX_BANK_CODE_TYPE ON MSTP.MSTP_BANK_MAPPING (BANK_CODE, CODE_TYPE);

COMMENT ON TABLE  MSTP.MSTP_BANK_MAPPING IS '行号映射表';
COMMENT ON COLUMN MSTP.MSTP_BANK_MAPPING.BANK_CODE IS '行号: CNAPS 12位 / CIPS BIC 11位';
COMMENT ON COLUMN MSTP.MSTP_BANK_MAPPING.BANK_NAME IS '行名';
COMMENT ON COLUMN MSTP.MSTP_BANK_MAPPING.CODE_TYPE IS '行号类型: CNAPS/CIPS';

-- ----------------------------------------------------------------------------
-- 3. 付款账号配置表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_PAYER_ACCOUNT_CONFIG (
    ID                  NUMBER(20)      NOT NULL,
    CHANNEL             VARCHAR2(10)    NOT NULL,
    PAYER_BANK_CODE     VARCHAR2(20)    NOT NULL,
    PAYER_BANK_NAME     VARCHAR2(200)   NOT NULL,
    PAYER_ACCOUNT_NO    VARCHAR2(32)    NOT NULL,
    PAYER_ACCOUNT_NAME  VARCHAR2(200)   NOT NULL,
    CURRENCY            VARCHAR2(3)     NOT NULL,
    IS_AUTHORIZED       NUMBER(1)       DEFAULT 0 NOT NULL,
    AUTHORIZED_TIME     TIMESTAMP(6),
    STATUS              VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    REMARK              VARCHAR2(500),
    IS_DELETED          NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY          VARCHAR2(50)    NOT NULL,
    CREATED_TIME        TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(50)    NOT NULL,
    UPDATED_TIME        TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYER_ACCOUNT_CONFIG PRIMARY KEY (ID),
    CONSTRAINT CK_PAYER_CHANNEL CHECK (CHANNEL IN ('CNAPS', 'CIPS')),
    CONSTRAINT CK_PAYER_AUTHORIZED CHECK (IS_AUTHORIZED IN (0, 1)),
    CONSTRAINT CK_PAYER_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_PAYER_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_CHANNEL_CURRENCY ON MSTP.MSTP_PAYER_ACCOUNT_CONFIG (CHANNEL, CURRENCY, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_PAYER_ACCOUNT_CONFIG IS '付款账号配置表';
COMMENT ON COLUMN MSTP.MSTP_PAYER_ACCOUNT_CONFIG.CHANNEL IS '支付渠道: CNAPS/CIPS';
COMMENT ON COLUMN MSTP.MSTP_PAYER_ACCOUNT_CONFIG.IS_AUTHORIZED IS '是否已授权: 0-否 1-是';
