-- ============================================================================
-- MSTP Approval & System Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 审批主表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_APPROVAL_RECORD (
    ID              NUMBER(20)      NOT NULL,
    APPROVAL_ID     VARCHAR2(40)    NOT NULL,
    BIZ_TYPE        VARCHAR2(20)    NOT NULL,
    BIZ_ID          NUMBER(20)      NOT NULL,
    OPERATION_TYPE  VARCHAR2(10)    NOT NULL,
    OPERATION_DATA  CLOB            NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'PENDING' NOT NULL,
    MAKER_ID        VARCHAR2(50)    NOT NULL,
    MAKER_TIME      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CHECKER_ID      VARCHAR2(50),
    CHECKER_TIME    TIMESTAMP(6),
    REJECT_REASON   VARCHAR2(500),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APPROVAL_RECORD PRIMARY KEY (ID),
    CONSTRAINT CK_AR_BIZ_TYPE CHECK (BIZ_TYPE IN ('ACCOUNT_MAPPING', 'BANK_MAPPING', 'PAYER_CONFIG')),
    CONSTRAINT CK_AR_OP_TYPE CHECK (OPERATION_TYPE IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT CK_AR_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CK_AR_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_APPROVAL_ID ON MSTP.MSTP_APPROVAL_RECORD (APPROVAL_ID);
CREATE INDEX MSTP.IDX_AR_BIZ_TYPE_STATUS ON MSTP.MSTP_APPROVAL_RECORD (BIZ_TYPE, STATUS);
CREATE INDEX MSTP.IDX_AR_MAKER_ID ON MSTP.MSTP_APPROVAL_RECORD (MAKER_ID);
CREATE INDEX MSTP.IDX_AR_CHECKER_ID ON MSTP.MSTP_APPROVAL_RECORD (CHECKER_ID);

COMMENT ON TABLE  MSTP.MSTP_APPROVAL_RECORD IS '审批主表';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.APPROVAL_ID IS '审批单号';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.BIZ_TYPE IS '业务类型: ACCOUNT_MAPPING/BANK_MAPPING/PAYER_CONFIG';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.OPERATION_TYPE IS '操作类型: CREATE/UPDATE/DELETE';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.OPERATION_DATA IS '操作数据(JSON格式,保存变更前后快照)';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.STATUS IS '审批状态: PENDING/APPROVED/REJECTED';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.MAKER_ID IS '制单人';
COMMENT ON COLUMN MSTP.MSTP_APPROVAL_RECORD.CHECKER_ID IS '审核人';

-- ----------------------------------------------------------------------------
-- 2. 用户表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_USER (
    ID              NUMBER(20)      NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    USER_NAME       VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100),
    STATUS          VARCHAR2(10)    DEFAULT 'ACTIVE' NOT NULL,
    PASSWORD_HASH   VARCHAR2(200),
    LAST_LOGIN_TIME TIMESTAMP(6),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT CK_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'LOCKED', 'DISABLED')),
    CONSTRAINT CK_USER_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_USER_ID ON MSTP.MSTP_USER (USER_ID, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_USER IS '用户表';
COMMENT ON COLUMN MSTP.MSTP_USER.USER_ID IS '用户ID(业务主键)';
COMMENT ON COLUMN MSTP.MSTP_USER.STATUS IS '状态: ACTIVE/LOCKED/DISABLED';
COMMENT ON COLUMN MSTP.MSTP_USER.PASSWORD_HASH IS '密码哈希(Local模式使用)';

-- ----------------------------------------------------------------------------
-- 3. 角色表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_ROLE (
    ID              NUMBER(20)      NOT NULL,
    ROLE_CODE       VARCHAR2(30)    NOT NULL,
    ROLE_NAME       VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    SOURCE          VARCHAR2(10)    DEFAULT 'LOCAL' NOT NULL,
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID),
    CONSTRAINT CK_ROLE_SOURCE CHECK (SOURCE IN ('LOCAL', 'EXTERNAL')),
    CONSTRAINT CK_ROLE_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_ROLE_CODE ON MSTP.MSTP_ROLE (ROLE_CODE, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_ROLE IS '角色表';
COMMENT ON COLUMN MSTP.MSTP_ROLE.ROLE_CODE IS '角色编码';
COMMENT ON COLUMN MSTP.MSTP_ROLE.SOURCE IS '来源: LOCAL/EXTERNAL';

-- ----------------------------------------------------------------------------
-- 4. 用户角色关联表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_USER_ROLE (
    ID              NUMBER(20)      NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    ROLE_CODE       VARCHAR2(30)    NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES MSTP.MSTP_USER(USER_ID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES MSTP.MSTP_ROLE(ROLE_CODE)
);

CREATE INDEX MSTP.IDX_UR_USER_ID ON MSTP.MSTP_USER_ROLE (USER_ID);
CREATE INDEX MSTP.IDX_UR_ROLE_CODE ON MSTP.MSTP_USER_ROLE (ROLE_CODE);

COMMENT ON TABLE  MSTP.MSTP_USER_ROLE IS '用户角色关联表';

-- ----------------------------------------------------------------------------
-- 5. 操作日志表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_AUDIT_LOG (
    ID              NUMBER(20)      NOT NULL,
    LOG_ID          VARCHAR2(40)    NOT NULL,
    USER_ID         VARCHAR2(50)    NOT NULL,
    USER_NAME       VARCHAR2(100)   NOT NULL,
    MODULE          VARCHAR2(30)    NOT NULL,
    ACTION          VARCHAR2(30)    NOT NULL,
    TARGET_TYPE     VARCHAR2(30),
    TARGET_ID       VARCHAR2(40),
    DETAIL          CLOB,
    CLIENT_IP       VARCHAR2(45),
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX MSTP.UK_AUDIT_LOG_ID ON MSTP.MSTP_AUDIT_LOG (LOG_ID);
CREATE INDEX MSTP.IDX_AL_USER_ID ON MSTP.MSTP_AUDIT_LOG (USER_ID);
CREATE INDEX MSTP.IDX_AL_MODULE ON MSTP.MSTP_AUDIT_LOG (MODULE);
CREATE INDEX MSTP.IDX_AL_CREATED_TIME ON MSTP.MSTP_AUDIT_LOG (CREATED_TIME);

COMMENT ON TABLE  MSTP.MSTP_AUDIT_LOG IS '操作日志表(仅追加,不可修改)';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.LOG_ID IS '日志唯一ID';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.MODULE IS '模块';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.ACTION IS '操作';
COMMENT ON COLUMN MSTP.MSTP_AUDIT_LOG.DETAIL IS '操作详情(JSON)';

-- ----------------------------------------------------------------------------
-- 6. 系统配置表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_SYS_CONFIG (
    ID              NUMBER(20)      NOT NULL,
    CONFIG_KEY      VARCHAR2(100)   NOT NULL,
    CONFIG_VALUE    VARCHAR2(500)   NOT NULL,
    CONFIG_GROUP    VARCHAR2(50)    NOT NULL,
    DESCRIPTION     VARCHAR2(200),
    IS_DELETED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(50)    NOT NULL,
    UPDATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SYS_CONFIG PRIMARY KEY (ID),
    CONSTRAINT CK_SC_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX MSTP.UK_CONFIG_KEY ON MSTP.MSTP_SYS_CONFIG (CONFIG_KEY, IS_DELETED);

COMMENT ON TABLE  MSTP.MSTP_SYS_CONFIG IS '系统配置表';
COMMENT ON COLUMN MSTP.MSTP_SYS_CONFIG.CONFIG_KEY IS '配置键';
COMMENT ON COLUMN MSTP.MSTP_SYS_CONFIG.CONFIG_VALUE IS '配置值';
COMMENT ON COLUMN MSTP.MSTP_SYS_CONFIG.CONFIG_GROUP IS '配置分组';
