-- ============================================================================
-- MSTP Transaction Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 支付指令表 (按月分区)
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_PAYMENT_INSTRUCTION (
    ID                  NUMBER(20)      NOT NULL,
    TXN_ID              VARCHAR2(40)    NOT NULL,
    SOURCE_MSG_ID       VARCHAR2(64)    NOT NULL,
    CHANNEL             VARCHAR2(10)    NOT NULL,
    PAYER_BANK_CODE     VARCHAR2(20)    NOT NULL,
    PAYER_BANK_NAME     VARCHAR2(200)   NOT NULL,
    PAYER_ACCOUNT_NO    VARCHAR2(32)    NOT NULL,
    PAYER_ACCOUNT_NAME  VARCHAR2(200)   NOT NULL,
    PAYEE_BANK_CODE     VARCHAR2(20)    NOT NULL,
    PAYEE_BANK_NAME     VARCHAR2(200)   NOT NULL,
    PAYEE_ACCOUNT_NO    VARCHAR2(32)    NOT NULL,
    PAYEE_ACCOUNT_NAME  VARCHAR2(200)   NOT NULL,
    AMOUNT              NUMBER(18,2)    NOT NULL,
    CURRENCY            VARCHAR2(3)     DEFAULT 'CNY' NOT NULL,
    STATUS              VARCHAR2(30)    NOT NULL,
    DOWNSTREAM_REF      VARCHAR2(64),
    ERROR_CODE          VARCHAR2(20),
    ERROR_MESSAGE       VARCHAR2(500),
    RETRY_COUNT         NUMBER(5)       DEFAULT 0 NOT NULL,
    NEXT_RETRY_TIME     TIMESTAMP(6),
    AUTH_CALLED         NUMBER(1)       DEFAULT 0 NOT NULL,
    IS_DELETED          NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_BY          VARCHAR2(50)    DEFAULT 'SYSTEM' NOT NULL,
    CREATED_TIME        TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(50)    DEFAULT 'SYSTEM' NOT NULL,
    UPDATED_TIME        TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYMENT_INSTRUCTION PRIMARY KEY (ID, CREATED_TIME),
    CONSTRAINT CK_PAY_CHANNEL CHECK (CHANNEL IN ('CNAPS', 'CIPS')),
    CONSTRAINT CK_PAY_STATUS CHECK (STATUS IN (
        'GCMS', 'VALIDATING', 'SENDING', 'SEND_FAILED',
        'CITIFT_PENDING', 'CITIFT_PENDING_TIMEOUT', 'CITIFT_SUCC',
        'LCP_PENDING', 'LCP_PENDING_TIMEOUT', 'LCP_CLEARED',
        'CIPS_PENDING', 'CIPS_PENDING_TIMEOUT', 'CIPS_CLEARED'
    )),
    CONSTRAINT CK_PAY_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT CK_PAY_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CK_PAY_AUTH CHECK (AUTH_CALLED IN (0, 1))
)
PARTITION BY RANGE (CREATED_TIME) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION P_202605 VALUES LESS THAN (TO_DATE('2026-06-01', 'YYYY-MM-DD'))
);

CREATE UNIQUE INDEX MSTP.UK_TXN_ID ON MSTP.MSTP_PAYMENT_INSTRUCTION (TXN_ID);
CREATE INDEX MSTP.IDX_PAY_SOURCE_MSG ON MSTP.MSTP_PAYMENT_INSTRUCTION (SOURCE_MSG_ID);
CREATE INDEX MSTP.IDX_PAY_STATUS ON MSTP.MSTP_PAYMENT_INSTRUCTION (STATUS);
CREATE INDEX MSTP.IDX_PAY_CREATED_TIME ON MSTP.MSTP_PAYMENT_INSTRUCTION (CREATED_TIME);
CREATE INDEX MSTP.IDX_PAY_PAYEE_ACCOUNT ON MSTP.MSTP_PAYMENT_INSTRUCTION (PAYEE_ACCOUNT_NO);

COMMENT ON TABLE  MSTP.MSTP_PAYMENT_INSTRUCTION IS '支付指令表';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.TXN_ID IS '交易唯一ID(幂等键)';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.SOURCE_MSG_ID IS '上游消息ID';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.CHANNEL IS '支付渠道: CNAPS/CIPS';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.STATUS IS '交易状态: GCMS/VALIDATING/SENDING/CITIFT_PENDING/CITIFT_SUCC/LCP_PENDING/LCP_CLEARED/CIPS_PENDING/CIPS_CLEARED及timeout变体';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.DOWNSTREAM_REF IS '下游返回参考号';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.RETRY_COUNT IS '重试次数';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_INSTRUCTION.AUTH_CALLED IS '是否已调用授权接口: 0-否 1-是';

-- ----------------------------------------------------------------------------
-- 2. 支付状态跟踪表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_PAYMENT_STATUS_LOG (
    ID              NUMBER(20)      NOT NULL,
    TXN_ID          VARCHAR2(40)    NOT NULL,
    FROM_STATUS     VARCHAR2(30),
    TO_STATUS       VARCHAR2(30)    NOT NULL,
    STATUS_TIME     TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    REMARK          VARCHAR2(500),
    CREATED_BY      VARCHAR2(50)    DEFAULT 'SYSTEM' NOT NULL,
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAYMENT_STATUS_LOG PRIMARY KEY (ID)
);

CREATE INDEX MSTP.IDX_PSL_TXN_ID ON MSTP.MSTP_PAYMENT_STATUS_LOG (TXN_ID);
CREATE INDEX MSTP.IDX_PSL_STATUS_TIME ON MSTP.MSTP_PAYMENT_STATUS_LOG (STATUS_TIME);

COMMENT ON TABLE  MSTP.MSTP_PAYMENT_STATUS_LOG IS '支付状态跟踪表';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.TXN_ID IS '交易ID';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.FROM_STATUS IS '原状态';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.TO_STATUS IS '新状态';
COMMENT ON COLUMN MSTP.MSTP_PAYMENT_STATUS_LOG.STATUS_TIME IS '状态变更时间';

-- ----------------------------------------------------------------------------
-- 3. 异常消息表
-- ----------------------------------------------------------------------------
CREATE TABLE MSTP.MSTP_MESSAGE_EXCEPTION (
    ID              NUMBER(20)      NOT NULL,
    MSG_ID          VARCHAR2(64)    NOT NULL,
    RAW_PAYLOAD     CLOB            NOT NULL,
    EXCEPTION_TYPE  VARCHAR2(20)    NOT NULL,
    ERROR_MESSAGE   VARCHAR2(500)   NOT NULL,
    STATUS          VARCHAR2(10)    DEFAULT 'PENDING' NOT NULL,
    RESOLVED_BY     VARCHAR2(50),
    RESOLVED_TIME   TIMESTAMP(6),
    CREATED_TIME    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MESSAGE_EXCEPTION PRIMARY KEY (ID),
    CONSTRAINT CK_ME_STATUS CHECK (STATUS IN ('PENDING', 'RESOLVED'))
);

CREATE INDEX MSTP.IDX_ME_MSG_ID ON MSTP.MSTP_MESSAGE_EXCEPTION (MSG_ID);
CREATE INDEX MSTP.IDX_ME_STATUS ON MSTP.MSTP_MESSAGE_EXCEPTION (STATUS);

COMMENT ON TABLE  MSTP.MSTP_MESSAGE_EXCEPTION IS '异常消息表';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.MSG_ID IS '原始消息ID';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.RAW_PAYLOAD IS '原始消息内容';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.EXCEPTION_TYPE IS '异常类型: FORMAT_ERROR/FIELD_MISSING/INVALID_ENUM/BIZ_ERROR/SYS_ERROR';
COMMENT ON COLUMN MSTP.MSTP_MESSAGE_EXCEPTION.STATUS IS '状态: PENDING/RESOLVED';
