-- ============================================================================
-- MSTP Schema Creation
-- Oracle 19c+
-- ============================================================================

CREATE USER MSTP IDENTIFIED BY "Mstp_2026!" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO MSTP;
GRANT CREATE TABLE TO MSTP;
GRANT CREATE SEQUENCE TO MSTP;
GRANT CREATE VIEW TO MSTP;
GRANT CREATE PROCEDURE TO MSTP;
GRANT CREATE TRIGGER TO MSTP;

ALTER USER MSTP DEFAULT TABLESPACE USERS;
ALTER USER MSTP QUOTA UNLIMITED ON USERS;
