-- ============================================================================
-- MSTP Sequences
-- All tables use Oracle Sequence for PK generation
-- ============================================================================

CREATE SEQUENCE MSTP.SEQ_ACCOUNT_MAPPING   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_BANK_MAPPING      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_PAYER_CONFIG      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_PAYMENT_INSTR     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_PAYMENT_STATUS    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_APPROVAL_RECORD   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_AUDIT_LOG         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_SYS_CONFIG        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_MESSAGE_EXCEPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_USER              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_ROLE              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MSTP.SEQ_USER_ROLE         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
