-- ============================================================================
-- MSTP Initial Data
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 初始角色
-- ----------------------------------------------------------------------------
INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'MAKER', '制单人', '可新增/编辑映射记录，查询数据', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'CHECKER', '审核人', '可审批映射记录，查询数据', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'ADMIN', '管理员', '拥有所有权限', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_ROLE (ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, SOURCE, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_ROLE.NEXTVAL, 'VIEWER', '观察者', '仅查询权限', 'LOCAL', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

-- ----------------------------------------------------------------------------
-- 2. 初始管理员用户 (密码: Admin@2026)
-- ----------------------------------------------------------------------------
INSERT INTO MSTP.MSTP_USER (ID, USER_ID, USER_NAME, EMAIL, STATUS, PASSWORD_HASH, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_USER.NEXTVAL, 'admin', '系统管理员', 'admin@mstp.local', 'ACTIVE',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
        0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

-- ----------------------------------------------------------------------------
-- 3. 初始用户角色关联
-- ----------------------------------------------------------------------------
INSERT INTO MSTP.MSTP_USER_ROLE (ID, USER_ID, ROLE_CODE, CREATED_BY, CREATED_TIME)
VALUES (MSTP.SEQ_USER_ROLE.NEXTVAL, 'admin', 'ADMIN', 'SYSTEM', SYSTIMESTAMP);

-- ----------------------------------------------------------------------------
-- 4. 初始系统配置
-- ----------------------------------------------------------------------------
INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.host', 'tcp://localhost:55555', 'SOLACE', 'Solace Broker地址', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.vpn', 'mstp-vpn', 'SOLACE', 'Solace消息VPN', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.queue', 'MSTP_PAYMENT_REQ_Q', 'SOLACE', '支付请求队列名', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.concurrent.consumers', '5', 'SOLACE', '初始并发消费者数', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'solace.max.consumers', '20', 'SOLACE', '最大并发消费者数', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.base-url', 'https://payment.internal/api/v1', 'PAYMENT', '下游支付API基础地址', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.connect-timeout', '5000', 'PAYMENT', '连接超时(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.read-timeout', '30000', 'PAYMENT', '读取超时(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.api.max-retry', '3', 'PAYMENT', '最大重试次数', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.polling.initial-interval', '5000', 'PAYMENT', '轮询初始间隔(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.polling.max-interval', '30000', 'PAYMENT', '轮询最大间隔(ms)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'payment.pending.timeout', '300', 'PAYMENT', 'Pending状态超时时间(秒)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'auth.provider', 'local', 'AUTH', '认证提供者: local/sso', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'auth.local.access-token-ttl', '30m', 'AUTH', 'Access Token有效期', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'rbac.provider', 'local', 'RBAC', '权限提供者: local/external', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MSTP.MSTP_SYS_CONFIG (ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_GROUP, DESCRIPTION, IS_DELETED, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
VALUES (MSTP.SEQ_SYS_CONFIG.NEXTVAL, 'rbac.sync.interval', '300', 'RBAC', '外部权限同步间隔(秒)', 0, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP);

COMMIT;
